repos:
- repo: https://github.com/python/black
  rev: stable
  hooks:
    - id: black

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: debug-statements
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  - id: check-merge-conflict
  - id: check-executables-have-shebangs
  - id: check-ast
  - id: check-yaml
  - id: no-commit-to-branch
  - id: flake8
    args: ['--exclude=docs/*', '--ignore=E501,W503,E203']

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.9.0
    hooks:
    - id: reorder-python-imports

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.4.0
  hooks:
    - id: python-check-mock-methods

